import { Kbd, Stack } from "@moto-ui/react";

export function NavigationKeys() {
	return (
		<Stack
			gap="8"
			align="center"
			direction="column"
		>
			<Stack gap="8">
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>↑</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>↓</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>←</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>→</Kbd.Item>
				</Kbd>
			</Stack>
			<Stack gap="8">
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>↵</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>⇧</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>⌥</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>⌘</Kbd.Item>
				</Kbd>
			</Stack>
			<Stack gap="8">
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>⇞</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>⇟</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>↖</Kbd.Item>
				</Kbd>
				<Kbd
					colorPalette="neutral"
					variant="secondary"
				>
					<Kbd.Item>↗</Kbd.Item>
				</Kbd>
			</Stack>
		</Stack>
	);
}
