export const size = {
  "2xs": {
    gap: "6px",
    height: "20px",
    fontSize: "12px",
    lineHeight: "16px",
    paddingInline: "8px",
    paddingBlock: "4px",
    borderRadius: "6px",
  },
  xs: {
    gap: "6px",
    height: "24px",
    fontSize: "13px",
    lineHeight: "16px",
    paddingBlock: "6px",
    paddingInline: "10px",
    borderRadius: "6px",
  },
  sm: {
    gap: "6px",
    height: "28px",
    fontSize: "14px",
    lineHeight: "20px",
    paddingBlock: "6px",
    paddingInline: "10px",
    borderRadius: "6px",
  },
  md: {
    gap: "6px",
    height: "32px",
    fontSize: "14px",
    lineHeight: "20px",
    paddingBlock: "8px",
    borderRadius: "8px",
    paddingInline: "8px",
  },
  lg: {
    gap: "6px",
    height: "36px",
    fontSize: "14px",
    lineHeight: "20px",
    paddingBlock: "10px",
    paddingInline: "10px",
    borderRadius: "8px",
  },
  xl: {
    gap: "40px",
    height: "48px",
    fontSize: "16px",
    lineHeight: "24px",
    paddingBlock: "12px",
    paddingInline: "12px",
    borderRadius: "10px",
  },
};
